// <auto-generated />
namespace DHD.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addfk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfk));
        
        string IMigrationMetadata.Id
        {
            get { return "201702240659041_add-fk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
