// <auto-generated />
namespace DHD.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update26 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update26));
        
        string IMigrationMetadata.Id
        {
            get { return "201704270846211_update26"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
